### ISSUE TITLE
建议添加：设置游戏exe路径 和 快速启动游戏 两个功能

### ISSUE THREAD

**Issue by 18601673727** [Xiaomony/NoitaSaveManager#1]

**Comment by Xiaomony** [comment]
已添加该功能 @18601673727
请查看[Release v3.2.0](https://github.com/Xiaomony/NoitArchiver-Rust_ver./releases/tag/v3.2.0)

**Comment by 18601673727** [comment]
@Xiaomony 非常感谢！
