### ISSUE TITLE
GUI 版本双击运行闪退

### ISSUE THREAD

**Issue by xja** [Xiaomony/NoitaSaveManager#2]
网吧环境。请问该如何定位问题？看了下事件查看器里面没有相关信息。

**Comment by Xiaomony** [comment]
使用的是Win10还是Win11？
> 如果是Win10，可以检查一下 **_控制面板-程序_** 中是否有安装 **_webview2_** ，如果未安装，前往[微软官网](https://developer.microsoft.com/en-us/microsoft-edge/webview2/?form=MA13LH#download-section)

**Comment by xja** [comment]
经确认确实如此，安装好 webview2 之后问题解决
